mysite/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_id>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('tag/<tag_slug>/', views.post_list, name='post_list_by_tag'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

mysite/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', '게시되지 않음'
        PUBLISHED = 'PB', '게시됨'

    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    slug = models.SlugField(max_length=200)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)
    status = models.CharField(
        choices=Status.choices, max_length=2, default=Status.DRAFT
    )

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=25)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return self.body

mysite/shop/models.py
from django.db import models

# Create your models here.

mysite/blog/forms.py
from django import forms
from django.utils import timezone

from .models import Comment


class EmailPostForm(forms.Form):
    sender = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

    def __init__(self, *args, **kwargs):
        super(CommentModelForm, self).__init__(*args, **kwargs)
        self.fields['name'].required = False
        self.fields['email'].required = False
        self.fields['body'].required = False

mysite/blog/views.py
from django.core import paginator
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
# Create your views here.
from django.shortcuts import render
from django.views.decorators.http import require_POST
from taggit.models import Tag

from .forms import EmailPostForm, CommentModelForm
from .models import Post


# Create your views here.
def post_list(request, tag_slug=None):
    posts = Post.objects.filter(status=Post.Status.PUBLISHED)
    page = request.GET.get('page')

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    paginator = Paginator(posts, 3)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page = 1
        page_obj = paginator.page(page)
    except EmptyPage:
        page = paginator.num_pages
        page_obj = paginator.page(page)

    return render(request, 'blog/post/list.html',
                  {'posts': posts,
                   'page_obj': page_obj,
                   'paginator': paginator})


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentModelForm(data=request.POST)
    comments = post.comments.filter(active=True)
    return render(request, 'blog/post/detail.html', {'post': post, 'form': form, 'comments': comments})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{data['sender']} has recommended {post.title}"
            message = f"hello {post_url}"
            send_mail(subject, message, [data['email']], [data['to']])
            sent = True
    else:
        form = EmailPostForm()
    comments = post.comments.filter(active=True)
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent, 'comments': comments})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    form = CommentModelForm(request.POST)
    comment = None
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return redirect(post)

    return render(request, 'blog/post/detail.html', {'post': post, 'form': form})

mysite/shop/views.py
from django.shortcuts import render

# Create your views here.

mysite/blog/templates/blog/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-9">
            {% block content %}
            {% endblock %}
        </div>
        <div class="col-3 bg-dark bg-gradient text-white" style="--bs-bg-opacity: .8;">
            <h2>Sidebar</h2>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>
</html>

mysite/blog/templates/blog/post/comment_form.html
<h3>Comment</h3>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Done">
</form>

mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div>
        <div class="border-bottom border-dark">
            <h3>{{ post.title }}</h3>
        </div>
        <br>
        <div class="position-relative">
            {{ post.body|linebreaks }}
        </div>
        <p><a href="{% url 'blog:post_share' post.id %}">Send this article to email</a></p>
        <div class="border-top border-dark">
            {% include 'blog/post/comment_form.html' %}
        </div>
        <br>
        <div class="border-top border-dark">
            {% for comment in comments %}
                <b>{{ comment.name }}</b> : <br>
                {{ comment.body |linebreaks }} <br>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

mysite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% block title %}Post List{% endblock %}
{% block content %}
    <h3>Post List</h3>
    {% for post in page_obj %}
        <div class="card" style="width: 20rem;">
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h5>
                <p class="card-text">{{ post.body }}<br>
                    Tags :  {% for tag in post.tags.all %}
                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %},{% endif %}
                    {% endfor %}</p>
            </div>
        </div>
    {% endfor %}
    <br>
    <p>Page</p>
    <ul style="display: flex;list-style :none">
        {% for page in paginator.page_range %}
            {% if page == page_obj.number %}
                <li style="margin: 3px;"><a style="text-decoration:none; color:black;"><b>{{ page }}</b></a>
                </li>
            {% else %}
                <li style="margin: 3px;"><a style="text-decoration:none; color:blue;"
                                            href="?page={{ page }}">{{ page }}</a>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block content %}
    {{ post.title }}<br>
    {{ post.body }}

    {% if sent %}
        <p>E-mail was sent</p>
    {% else %}
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send">
        </form>
    {% endif %}
{% endblock %}